repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^k8s/charts/tokenplace-relay/templates/
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--ignore-words", "dict/allow.txt", "--skip", "*.lock,package-lock.json,desktop/package-lock.json,*.svg,webapp/static/js/*"]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture
        args: [".", "--min-confidence", "80", "--exclude", "node_modules,desktop/node_modules"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-lll", "-x", "tests"]
        additional_dependencies:
          - pbr
  - repo: local
    hooks:
      - id: run-checks
        name: run project checks
        entry: scripts/checks.sh
        language: script
        pass_filenames: false
