version: '3.8'

services:
  relay:
    build:
      context: .
      dockerfile: docker/Dockerfile.relay
    ports:
      - "5000:5000"
    environment:
      - PLATFORM=${PLATFORM:-linux}
      - ENV=${ENV:-development}
      - SERVER_URL=${SERVER_URL:-http://localhost:5000}
    restart: unless-stopped
