version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
