ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: staging.token.place
  tls:
    enabled: true
    secretName: tokenplace-staging-tls
