ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
  hosts:
    - host: token.place
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true
    secretName: tokenplace-prod-tls
