apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokenplace-relay
  labels:
    app: tokenplace-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokenplace-relay
  template:
    metadata:
      labels:
        app: tokenplace-relay
    spec:
      containers:
      - name: relay
        image: tokenplace-relay:latest
        ports:
        - containerPort: 5000
        env:
        - name: PLATFORM
          value: "linux"
        - name: ENV
          value: "production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
