{{- if .Values.networkPolicy.enabled }}
{{- $np := .Values.networkPolicy }}
{{- $gpu := .Values.gpuExternalName }}
{{- $headless := $gpu.headless }}
{{- $useHeadless := or $gpu.useHeadless $headless.enabled }}
{{- $hasHeadless := and $useHeadless (gt (len $headless.addresses) 0) }}
{{- $hasExternal := and (not $useHeadless) (ne (default "" $gpu.host) "") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tokenplace-relay.fullname" . }}-deny-all
  labels:
    {{- include "tokenplace-relay.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tokenplace-relay.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if $np.extraIngress }}
    {{- range $np.extraIngress }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- else }}
    []
    {{- end }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if $hasHeadless }}
    {{- range $headless.addresses }}
    - to:
        - ipBlock:
            cidr: {{ printf "%s/32" . }}
      ports:
        - protocol: TCP
          port: {{ $gpu.port }}
    {{- end }}
    {{- else if $hasExternal }}
    - to:
        - ipBlock:
            cidr: {{ $np.externalNameCIDR }}
      ports:
        - protocol: TCP
          port: {{ $gpu.port }}
    {{- end }}
    {{- range $np.extraEgress }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
