{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tokenplace-relay.fullname" . }}
  labels:
    {{- include "tokenplace-relay.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "tokenplace-relay.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.traefikNamespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
  {{- $allowDns := .Values.networkPolicy.allowDNS -}}
  {{- $cidrs := .Values.networkPolicy.gpuServerCIDRs -}}
  egress:
    {{- if or $allowDns (gt (len $cidrs) 0) }}
    {{- if $allowDns }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- range $cidr := $cidrs }}
    - to:
        - ipBlock:
            cidr: {{ $cidr }}
      ports:
        - protocol: TCP
          port: {{ $.Values.upstream.port }}
    {{- end }}
    {{- else }} []
    {{- end }}
{{- end }}
