apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tokenplace-relay.fullname" . }}-pdb
  labels:
    {{- include "tokenplace-relay.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "tokenplace-relay.selectorLabels" . | nindent 6 }}
