replicaCount: 1

image:
  repository: ghcr.io/example/tokenplace-relay
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

service:
  type: ClusterIP
  port: 5010
  targetPort: 5010

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: relay.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - relay.example.com
      secretName: relay-tls

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

env:
  relayPort: 5010
  upstream:
    url: http://gpu-server:8000
  additional: []

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

gpuExternalName:
  enabled: true
  host: gpu-box.example.com
  port: 8000
  headless:
    enabled: false
    ip: ""
    port: 8000

networkPolicy:
  enabled: true
  traefikNamespaces:
    - traefik
  allowDns: true
  gpuServer:
    cidrs:
      - 203.0.113.10/32

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
