name: Build Relay Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - Dockerfile
      - docker/relay/**
      - relay.py
      - config/requirements_relay.txt
      - .github/workflows/build.yml
      - deploy/charts/tokenplace-relay/**
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags
        id: meta
        run: |
          set -euo pipefail
          SHORT_SHA="${GITHUB_SHA::7}"
          OWNER_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${OWNER_LOWER}/tokenplace-relay"
          TAGS="${IMAGE}:sha-${SHORT_SHA}"

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION_TAG="${GITHUB_REF_NAME}"
            TAGS+=$'\n'"${IMAGE}:${VERSION_TAG}"
            echo "version=${VERSION_TAG}" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAGS+=$'\n'"${IMAGE}:latest"
            echo "version=latest" >> "$GITHUB_OUTPUT"
          fi

          echo "image=${IMAGE}" >> "$GITHUB_OUTPUT"
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"
          echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.title=tokenplace-relay
            org.opencontainers.image.description=Relay service for token.place
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
