name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Prepare Raspberry Pi cgroups
        id: prep
        run: |
          set +e
          sudo bash scripts/prepare-pi-cgroups.sh
          echo "rc=$?" >> "$GITHUB_OUTPUT"
          exit 0
      - name: Stop for reboot
        if: steps.prep.outputs.rc == '2'
        run: echo "Cgroup configuration updated. Reboot runner and re-run job."
      - name: Validate dependency compatibility
        run: python scripts/validate_dependencies.py
        if: steps.prep.outputs.rc != '2'
      - name: Install Python dependencies
        if: steps.prep.outputs.rc != '2'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright browsers
        if: steps.prep.outputs.rc != '2'
        run: playwright install
      - name: Install Node.js dependencies
        if: steps.prep.outputs.rc != '2'
        run: npm ci
      - name: Run tests
        if: steps.prep.outputs.rc != '2'
        run: ./run_all_tests.sh
        env:
          TEST_COVERAGE: '1'
      - name: Upload coverage reports to Codecov
        if: steps.prep.outputs.rc != '2'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
